# Generated by Django 4.1.4 on 2022-12-17 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(7)])),
                ('files', models.FileField(upload_to='', validators=[file.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'xls', 'pdf', 'pptx', 'ppt', 'pptm', 'png', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
        ),
    ]
