# Generated by Django 4.1.4 on 2022-12-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Verify',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
