# Generated by Django 4.1.4 on 2022-12-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='verify_file_access',
            field=models.BooleanField(default=False),
        ),
    ]
