# Generated by Django 4.1.4 on 2022-12-16 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
        ),
    ]
