# Generated by Django 4.1.4 on 2022-12-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_catalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
