# Generated by Django 4.1.4 on 2022-12-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='file',
        ),
    ]
