# Generated by Django 4.1.4 on 2022-12-16 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_delete_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])])),
            ],
        ),
    ]
