# Generated by Django 4.1.4 on 2022-12-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_remove_catalog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
