# Generated by Django 4.1.4 on 2022-12-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_post_delete_somedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtensionValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
