# Generated by Django 4.1.4 on 2022-12-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_fileextensionvalidator_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
