# Generated by Django 4.1.4 on 2022-12-17 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_catalog_delete_fileextensionvalidator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'xls', 'pdf', 'pptx', 'ppt', 'pptm', 'png', 'jpeg'])]),
        ),
    ]
