# Generated by Django 4.1.4 on 2022-12-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_verify_customuser_verify_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_user_access',
            field=models.BooleanField(default=False, verbose_name='Уровень доступа сотрудника - расширенный'),
        ),
    ]
