# Generated by Django 4.1.4 on 2022-12-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otdel',
            field=models.CharField(choices=[('Коммерческий', 'Коммерческий'), ('Финансовый', 'Финансовый'), ('Маркетинговый', 'Маркетинговый')], default=1, max_length=255, verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
